/**
 * Gap analysis vs https://specification.website — what Legible checks today
 * vs what remains. Used as a roadmap for new detectors and site checks.
 */
export const SPEC_WEBSITE_ROADMAP = {
  implemented: [
    "foundations/open-graph (completeness, absolute URLs, twitter:card)",
    "foundations/theme-color",
    "foundations/color-scheme",
    "foundations/meta-viewport (zoom blocking)",
    "foundations/canonical-url (missing, malformed, conflict)",
    "foundations/title (length)",
    "foundations/meta-description (length)",
    "accessibility/skip-links",
    "accessibility/semantic-html (main landmark)",
    "accessibility/link-text",
    "accessibility/empty-links-buttons (links + buttons)",
    "accessibility/form-labels",
    "accessibility/document-language (inline lang)",
    "accessibility/image-alt-text (linked empty alt)",
    "security/subresource-integrity",
    "security/permissions-policy",
    "security/https-tls (HTTP redirect)",
    "security/content-security-policy (unsafe directives, reporting)",
    "performance/compression",
    "performance/cache-control (fingerprinted assets)",
    "performance/lazy-loading (LCP heuristic)",
    "agent-readiness/llms-txt",
    "agent-readiness/robots-for-ai-crawlers",
    "agent-readiness/link-headers",
    "agent-readiness/mcp-and-tool-discovery",
    "seo/breadcrumbs (BreadcrumbList JSON-LD)",
    "seo/structured-data (schema validation)",
    "seo/xml-sitemaps (size limit)",
    "privacy/privacy-policy (dead link)",
    "resilience/error-pages (404 helpfulness)",
    "foundations/favicons (apple-touch-icon)",
  ],
  deferred: [
    "accessibility/color-contrast",
    "accessibility/keyboard-navigation",
    "accessibility/focus-indicators",
    "accessibility/reduced-motion",
    "seo/server-side-rendering",
    "i18n/hreflang-in-sitemap",
    "agent-readiness/tdmrep",
    "resilience/pwa-manifest",
    "privacy/cookie-consent",
    "security/cross-origin-isolation",
    "security/dnssec",
  ],
} as const;
